#!/usr/bin/env node
/* Writes web/data-fixture/FIXTURE_rates_demo.json: INVENTED numbers in the shape the real
   cube will have (the doj_core column layout: precomputed month, quarter and fy rows, with rate
   numerators and a shared denominator per D-019 method). It stands in for the cube only so the shell
   can be seen working. The arithmetic here plays the cube's role; the browser does none of it.
   Deterministic: the same run always writes the same file. Usage: node web/tools/make-fixture.js */
'use strict';
const fs = require('fs');
const path = require('path');
const P = require('../assets/js/periods.js');

const FIRST = '2011-10', LAST = '2026-07';
const OUT = path.join(__dirname, '..', 'data-fixture', 'FIXTURE_rates_demo.json');

let seed = 20260930;
function rand() { seed = (seed * 1103515245 + 12345) % 2147483648; return seed / 2147483648; }

// Invented monthly series around a round base of 1,000 so no one mistakes it for DOJ data.
const months = P.listMonths(FIRST, LAST);
const hc = {}, dep = {}, quit = {};
months.forEach((m, i) => {
  hc[m] = Math.round(1000 + 60 * Math.sin(i / 20) + 30 * rand());
  dep[m] = Math.round(8 + 6 * rand() + (P.parseMonth(m).m === 9 ? 6 : 0));
  quit[m] = Math.round(dep[m] * (0.3 + 0.2 * rand()));
});
const provisional = new Set(months.slice(-3));
const flow = { attrition: dep, quit: quit };

const sum = (ms, s) => ms.reduce((a, m) => a + s[m], 0);
const mean = (ms, s) => sum(ms, s) / ms.length;
const r4 = v => Math.round(v * 10000) / 10000;

// Same column names and meanings as the doj_core cube (warehouse/cubes/doj_core.meta.json), fewer columns.
function row(grain, key) {
  const b = P.periodBounds(key);
  const last = b.end < LAST ? b.end : LAST;           // last published month
  const inPeriod = P.listMonths(b.start, last);
  const partial = b.end > LAST;
  const r = {
    entity: 'DOJ', grain, period: key,
    fiscal_year: P.fiscalYear(b.start), fiscal_quarter: grain === 'fy' ? null : P.fiscalQuarter(b.start),
    period_first_month: b.start, period_last_month: last,
    months_in_period: P.monthsBetween(b.start, b.end), months_published: inPeriod.length,
    time_basis: 'effective', provisional: inPeriod.some(m => provisional.has(m)), partial,
    headcount: hc[last],                   // stock: the period's last published month
    departures: sum(inPeriod, dep),        // flow: summed
    sep_quit: sum(inPeriod, quit)
  };
  // A. trailing 12 months ending in the last published month; none before Sep 2012
  const t12 = P.listMonths(P.addMonths(last, -11), last);
  const aOk = t12[0] >= FIRST;
  // B. fiscal year only, complete years only
  const bOk = grain === 'fy' && !partial;
  for (const [measure, s] of Object.entries(flow)) {
    r[measure + '_a_num'] = aOk ? sum(t12, s) : null;
    r[measure + '_b_num'] = bOk ? sum(inPeriod, s) : null;
    // C. annualized per period over its published months
    r[measure + '_c_num'] = r4(sum(inPeriod, s) * 12 / inPeriod.length);
  }
  r.rate_a_den = aOk ? r4(mean(t12, hc)) : null;
  r.rate_a_months = aOk ? 12 : null;
  r.rate_b_den = bOk ? r4(mean(inPeriod, hc)) : null;
  r.rate_b_months = bOk ? 12 : null;
  r.rate_c_den = r4(mean(inPeriod, hc));
  r.rate_c_months = inPeriod.length;
  for (const m of ['a', 'b', 'c']) r['rate_' + m + '_small_base'] = r['rate_' + m + '_den'] === null ? null : r['rate_' + m + '_den'] < 30;
  return r;
}

const objs = [];
for (const grain of P.GRAINS) {
  const keys = [...new Set(months.map(m => P.periodKey(m, grain)))];
  keys.forEach(k => objs.push(row(grain, k)));
}
const columns = Object.keys(objs[0]);

const out = {
  FIXTURE: true,
  notice: 'FIXTURE. INVENTED NUMBERS. NOT OPM DATA. For seeing the dashboard shell work only. Generated by web/tools/make-fixture.js in the doj_core column layout.',
  cube: 'FIXTURE_rates_demo',
  range: { first_month: FIRST, last_month: LAST },
  columns,
  rows: objs.map(o => columns.map(c => o[c]))
};
fs.writeFileSync(OUT, JSON.stringify(out) + '\n');
console.log('wrote', path.relative(process.cwd(), OUT), objs.length, 'rows');
